vich_uploader:
    db_driver: orm

    mappings:
        item_image:
            uri_prefix: /images/items
            upload_destination: '%kernel.project_dir%/public/images/items'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        editor_image:
            uri_prefix: /images/editor
            upload_destination: '%kernel.project_dir%/public/images/editor'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
