vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        game_image:
            uri_prefix: /images/games
            upload_destination: '%kernel.project_dir%/public/images/games'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        editor_image:
            uri_prefix: /images/editor
            upload_destination: '%kernel.project_dir%/public/images/editor'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
        dev_image:
            uri_prefix: /images/developper
            upload_destination: '%kernel.project_dir%/public/images/developper'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
