controllers:
    resource: ../../src/Controller/
    type: annotation

logout:
    path: /logout

controllers_back:
  resource: ../../src/Controller/Back
  type: annotation
  prefix: /admin

controllers_front:
  resource: ../../src/Controller/Front
  type: annotation
  options:
    expose: true

